[colors.normal]
black = "#151515"
blue = "#6A9FB5"
cyan = "#75B5AA"
green = "#90A959"
magenta = "#AA759F"
red = "#AC4142"
white = "#D0D0D0"
yellow = "#F4BF75"

[colors.primary]
background = "#151515"
foreground = "#d0d0d0"

[font]
size = 6

[font.bold]
family = "JetBrains Mono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrains Mono"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[shell]
program = "/bin/zsh"

[window.padding]
x = 20
y = 15
